AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  da-caselaw-docx-strip-author

  TNA Caselaw DOCX Author Metadata Stripping Lambda

Globals:
  Function:
    Timeout: 10

Parameters:
  AwsBucketName:
    Description: "PRIVATE_ASSET_BUCKET"
    Type: "String"
  PublicAssetBucket:
    Description: "PUBLIC_ASSET_BUCKET"
    Type: "String"
  RollbarEnv:
    Description: "ROLLBAR_ENV"
    Type: "String"
  RollbarToken:
    Description: "ROLLBAR_TOKEN"
    Type: "String"
  VpcSubnetId0:
    Description: "VPC Subnet ID 0"
    Type: "String"
  VpcSubnetId1:
    Description: "VPC Subnet ID 1"
    Type: "String"
  VpcSubnetId2:
    Description: "VPC Subnet ID 2"
    Type: "String"
  VpcSecurityGroupId:
    Description: "VPC Security Group ID"
    Type: "String"


Resources:
  TNACaselawDocxStripAuthorFunctionZip:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_strip_docx/
      Handler: handler.lambda_handler
      Runtime: python3.12
      MemorySize: 256
      Architectures:
        - x86_64
      Timeout: 30
      Environment:
        Variables:
          PRIVATE_ASSET_BUCKET: !Ref AwsBucketName
          PUBLIC_ASSET_BUCKET: !Ref PublicAssetBucket
          ROLLBAR_ENV: !Ref RollbarEnv
          ROLLBAR_TOKEN: !Ref RollbarToken
      VpcConfig:
        SubnetIds:
          - !Ref VpcSubnetId0
          - !Ref VpcSubnetId1
          - !Ref VpcSubnetId2
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId

  TNACaselawDocxStripAuthorFunctionContainer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: lambda_strip_docx/
      ImageUri: .
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          PRIVATE_ASSET_BUCKET: !Ref AwsBucketName
          PUBLIC_ASSET_BUCKET: !Ref PublicAssetBucket
          ROLLBAR_ENV: !Ref RollbarEnv
          ROLLBAR_TOKEN: !Ref RollbarToken
      VpcConfig:
        SubnetIds:
          - !Ref VpcSubnetId0
          - !Ref VpcSubnetId1
          - !Ref VpcSubnetId2
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId

Outputs:
  TNACaselawDocxStripAuthorFunctionZip:
    Description: "TNA Caselaw DOCX Strip Author Lambda Function (Zip) ARN"
    Value: !GetAtt TNACaselawDocxStripAuthorFunctionZip.Arn
  TNACaselawDocxStripAuthorFunctionContainer:
    Description: "TNA Caselaw DOCX Strip Author Lambda Function (Container) ARN"
    Value: !GetAtt TNACaselawDocxStripAuthorFunctionContainer.Arn
