name: Deploy DOCX Strip Author Lambda to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      - uses: aws-actions/setup-sam@f664fad9e12492edfc187a31f575537dfbb0ff63 # v2
      - uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_STAGING_ROLE_ARN }}
          aws-region: eu-west-2
      - run: sam build --use-container -m lambda_strip_docx/requirements.txt
      - run: >
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name da-caselaw-docx-strip-author --s3-bucket ingester-test-2 --capabilities CAPABILITY_IAM --region eu-west-2 --parameter-overrides
          AwsBucketName=${{ vars.PRIVATE_ASSET_BUCKET }}
          PublicAssetBucket=${{ vars.PUBLIC_ASSET_BUCKET }}
          RollbarEnv=${{ vars.ROLLBAR_ENV }}
          RollbarToken=${{ secrets.ROLLBAR_TOKEN }}
          VpcSubnetId0=${{ vars.VPC_SUBNET_ID_0 }}
          VpcSubnetId1=${{ vars.VPC_SUBNET_ID_1 }}
          VpcSubnetId2=${{ vars.VPC_SUBNET_ID_2 }}
          VpcSecurityGroupId=${{ vars.VPC_SECURITY_GROUP_ID }}
