name: Build, Deploy, and Trigger Terraform Apply
env:
  # Make these available to all jobs so the workflow is reusable across repos/environments.
  # Allow overriding LAMBDA_FUNCTION_NAME in repository secrets; fallback to the known default name.
  LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME || 'document-cleanser-lambda' }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
on:
  push:
    branches:
      - main
      - docker-build-and-deploy
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build and deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs:
  build-deploy:
    environment: ${{ github.event.inputs.environment || 'staging' }}
    name: Build, Push, and Deploy Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      pull-requests: read
    outputs:
      image_tag: ${{ steps.set_env.outputs.image_tag }}
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment variables
        id: set_env
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          # By default, environment is staging unless explicitly set by user in workflow_dispatch.
          if [ -z "$ENVIRONMENT" ]; then
            ENVIRONMENT="staging"
          fi

          # For production, require a tag and use the tag name as IMAGE_TAG
          if [ "$ENVIRONMENT" = "production" ]; then
            if [[ "$GITHUB_REF" != refs/tags/v* ]]; then
              echo "Error: Production deploys must use a GitHub release tag (refs/tags/v*) as the reference."
              exit 1
            fi
            IMAGE_TAG="$GITHUB_REF_NAME"
          else
            IMAGE_TAG="$GITHUB_SHA"
          fi

          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Install Wiz CLI
        run: |
          curl -o wizcli https://wizcli.app.wiz.io/wizcli
          chmod +x wizcli

      - name: Authenticate to Wiz API
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

      - name: Scan Dockerfile with Wiz CLI
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.set_env.outputs.image_tag }}
        run: |
          ./wizcli iac scan --path lambda_strip_docx --name "$ECR_REPOSITORY-$IMAGE_TAG"
      - name: Build and tag Docker image (with build cache)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ secrets.DOCKER_CONTEXT || 'lambda_strip_docx/' }}
          file: ${{ secrets.DOCKER_FILE || 'lambda_strip_docx/Dockerfile' }}
          push: false
          load: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.set_env.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.set_env.outputs.image_tag }}

      - name: Wiz Docker Scan
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.set_env.outputs.image_tag }}
        run: |
          ./wizcli docker scan --image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.set_env.outputs.image_tag }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Wiz Docker Tag
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.set_env.outputs.image_tag }}
        run: |
          ./wizcli docker tag --image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Update Lambda code
        env:
          LAMBDA_NAME: ${{ env.LAMBDA_FUNCTION_NAME }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.set_env.outputs.image_tag }}
        run: |
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          echo "Updating Lambda '${LAMBDA_NAME}' to image ${IMAGE_URI}"
          aws lambda update-function-code --function-name "$LAMBDA_NAME" --image-uri "$IMAGE_URI"
