name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run plan against"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
  push:
    branches: [main]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"

env:
  AWS_REGION: eu-west-2
  TERRAFORM_VERSION: 1.9.0
  TF_IN_AUTOMATION: true

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'staging' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-TerraformPlan
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: true
      - name: Terraform Init
        run: |
          terraform init -input=false -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}"
        working-directory: terraform
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: terraform
      - name: Terraform Plan
        run: |
          terraform plan
        working-directory: terraform
        env:
          TF_VAR_caselaw_vpc_id: ${{ secrets.TF_VAR_caselaw_vpc_id }}
          TF_VAR_unpublished_assets_bucket_name: ${{ secrets.TF_VAR_unpublished_assets_bucket_name }}
          TF_VAR_unpublished_assets_kms_key_arn: ${{ secrets.TF_VAR_unpublished_assets_kms_key_arn }}
          TF_VAR_s3_prefix_list_id: ${{ secrets.TF_VAR_s3_prefix_list_id }}
          # TF_VAR_legacy_kms_key_arns: ${{ secrets.TF_VAR_legacy_kms_key_arns }}
